#!/usr/bin/env python3
"""
Extract overlay pages from .AI files as transparent PNGs.

Finds any .ai file in public/overlays/, renders each page
as a transparent PNG at 3x resolution, and writes a manifest
file listing them for the React app.

Requirements: pip install pymupdf
"""

import sys
import os
import json
import glob

try:
    import fitz  # pymupdf
except ImportError:
    print("ERROR: pymupdf is not installed.")
    print("Run: pip install pymupdf --break-system-packages")
    sys.exit(1)

OVERLAYS_DIR = os.path.join(os.path.dirname(__file__), "public", "overlays")
MANIFEST_PATH = os.path.join(OVERLAYS_DIR, "manifest.json")
SCALE = 3

def extract():
    # Find .ai files
    ai_files = glob.glob(os.path.join(OVERLAYS_DIR, "*.ai"))

    if not ai_files:
        print(f"No .ai files found in {OVERLAYS_DIR}")
        print("Drop your .AI file there and re-run.")
        # Write empty manifest so the app doesn't break
        with open(MANIFEST_PATH, "w") as f:
            json.dump({"overlays": []}, f)
        return

    # Clean out old PNGs generated by this script
    old_pngs = glob.glob(os.path.join(OVERLAYS_DIR, "overlay-*.png"))
    for old in old_pngs:
        os.remove(old)
        print(f"  Removed old {os.path.basename(old)}")

    all_overlays = []

    for ai_path in sorted(ai_files):
        ai_name = os.path.basename(ai_path)
        print(f"\nProcessing: {ai_name}")

        try:
            doc = fitz.open(ai_path)
        except Exception as e:
            print(f"  ERROR: Could not open {ai_name}: {e}")
            print("  Make sure the file was saved with 'Create PDF Compatible File' checked.")
            continue

        print(f"  Pages: {doc.page_count}")

        for i in range(doc.page_count):
            page = doc[i]
            pix = page.get_pixmap(matrix=fitz.Matrix(SCALE, SCALE), alpha=True)

            filename = f"overlay-{len(all_overlays) + 1}.png"
            output_path = os.path.join(OVERLAYS_DIR, filename)
            pix.save(output_path)

            all_overlays.append(filename)
            print(f"  Page {i + 1}: {pix.width}x{pix.height} → {filename}")

        doc.close()

    # Write manifest
    manifest = {"overlays": all_overlays}
    with open(MANIFEST_PATH, "w") as f:
        json.dump(manifest, f, indent=2)

    print(f"\nDone! {len(all_overlays)} overlay(s) extracted.")
    print(f"Manifest written to {MANIFEST_PATH}")


if __name__ == "__main__":
    extract()
