import { useState, useRef, useEffect, useCallback } from 'react'

function App() {
  const [screen, setScreen] = useState('loading')
  const [overlayImages, setOverlayImages] = useState([])
  const [previewIndex, setPreviewIndex] = useState(0)
  const [capturedImage, setCapturedImage] = useState(null)
  const [cameraError, setCameraError] = useState(null)
  const [loadingStatus, setLoadingStatus] = useState('Loading overlays...')

  const videoRef = useRef(null)
  const canvasRef = useRef(null)
  const animFrameRef = useRef(null)
  const streamRef = useRef(null)

  // Load overlays from manifest and start camera
  useEffect(() => {
    let cancelled = false

    async function init() {
      try {
        // Load manifest generated by extract-overlays.py
        const manifestRes = await fetch('/overlays/manifest.json')
        if (!manifestRes.ok) {
          setLoadingStatus('No manifest found. Run: npm run extract')
          return
        }
        const manifest = await manifestRes.json()

        if (!manifest.overlays || manifest.overlays.length === 0) {
          setLoadingStatus('No overlays found. Drop a .AI file in public/overlays/ and restart.')
          return
        }

        const images = []

        for (const filename of manifest.overlays) {
          if (cancelled) return
          setLoadingStatus(`Loading ${filename}...`)

          const img = await new Promise((resolve, reject) => {
            const image = new Image()
            image.onload = () => resolve(image)
            image.onerror = () => reject(new Error(`Failed to load ${filename}`))
            image.src = `/overlays/${filename}`
          })

          images.push({
            img,
            width: img.naturalWidth,
            height: img.naturalHeight,
            filename,
          })
        }

        if (cancelled) return

        setOverlayImages(images)
        setLoadingStatus('Starting camera...')
        await startCamera()

      } catch (err) {
        console.error('Init error:', err)
        setLoadingStatus(`Error: ${err.message}`)
      }
    }

    init()

    return () => {
      cancelled = true
      stopCamera()
    }
  }, [])

  const startCamera = async () => {
    try {
      setCameraError(null)
      const stream = await navigator.mediaDevices.getUserMedia({
        video: {
          width: { ideal: 1920 },
          height: { ideal: 1920 },
          facingMode: 'environment'
        },
        audio: false
      })
      streamRef.current = stream
      if (videoRef.current) {
        videoRef.current.srcObject = stream
        await videoRef.current.play()
      }
      setScreen('booth')
    } catch (err) {
      console.error('Camera error:', err)
      setCameraError('Could not access camera. Allow camera permissions and try again.')
      setScreen('booth')
    }
  }

  const stopCamera = () => {
    if (streamRef.current) {
      streamRef.current.getTracks().forEach(t => t.stop())
      streamRef.current = null
    }
    if (animFrameRef.current) {
      cancelAnimationFrame(animFrameRef.current)
      animFrameRef.current = null
    }
  }

  const cyclePreview = () => {
    setPreviewIndex(i => (i + 1) % overlayImages.length)
  }

  // Crop video to match overlay aspect ratio (cover mode)
  const getCoverCrop = useCallback((videoWidth, videoHeight, targetWidth, targetHeight) => {
    const targetAspect = targetWidth / targetHeight
    const videoAspect = videoWidth / videoHeight

    let sourceX, sourceY, sourceWidth, sourceHeight

    if (videoAspect > targetAspect) {
      sourceHeight = videoHeight
      sourceWidth = videoHeight * targetAspect
      sourceX = (videoWidth - sourceWidth) / 2
      sourceY = 0
    } else {
      sourceWidth = videoWidth
      sourceHeight = videoWidth / targetAspect
      sourceX = 0
      sourceY = (videoHeight - sourceHeight) / 2
    }

    return { sourceX, sourceY, sourceWidth, sourceHeight }
  }, [])

  // Animation loop
  const drawFrame = useCallback(() => {
    const canvas = canvasRef.current
    const video = videoRef.current

    if (!canvas || !video || video.readyState < 2 || overlayImages.length === 0) {
      animFrameRef.current = requestAnimationFrame(drawFrame)
      return
    }

    const overlay = overlayImages[previewIndex]
    const ctx = canvas.getContext('2d')

    if (canvas.width !== overlay.width || canvas.height !== overlay.height) {
      canvas.width = overlay.width
      canvas.height = overlay.height
    }

    const crop = getCoverCrop(video.videoWidth, video.videoHeight, overlay.width, overlay.height)
    ctx.drawImage(video,
      crop.sourceX, crop.sourceY, crop.sourceWidth, crop.sourceHeight,
      0, 0, canvas.width, canvas.height
    )

    if (overlay.img.complete && overlay.img.naturalWidth > 0) {
      ctx.drawImage(overlay.img, 0, 0, canvas.width, canvas.height)
    }

    animFrameRef.current = requestAnimationFrame(drawFrame)
  }, [overlayImages, previewIndex, getCoverCrop])

  useEffect(() => {
    if (screen === 'booth' && overlayImages.length > 0) {
      animFrameRef.current = requestAnimationFrame(drawFrame)
    }
    return () => {
      if (animFrameRef.current) {
        cancelAnimationFrame(animFrameRef.current)
      }
    }
  }, [screen, drawFrame, overlayImages])

  // Capture — random overlay
  const capture = () => {
    const canvas = canvasRef.current
    const video = videoRef.current
    if (!canvas || !video || overlayImages.length === 0) return

    const randomIndex = Math.floor(Math.random() * overlayImages.length)
    const overlay = overlayImages[randomIndex]

    const ctx = canvas.getContext('2d')
    canvas.width = overlay.width
    canvas.height = overlay.height

    const crop = getCoverCrop(video.videoWidth, video.videoHeight, overlay.width, overlay.height)
    ctx.drawImage(video,
      crop.sourceX, crop.sourceY, crop.sourceWidth, crop.sourceHeight,
      0, 0, canvas.width, canvas.height
    )

    if (overlay.img.complete && overlay.img.naturalWidth > 0) {
      ctx.drawImage(overlay.img, 0, 0, canvas.width, canvas.height)
    }

    const dataUrl = canvas.toDataURL('image/png')
    setCapturedImage(dataUrl)
    stopCamera()
    setScreen('review')
  }

  const download = () => {
    if (!capturedImage) return
    const a = document.createElement('a')
    a.href = capturedImage
    a.download = `magazine-cover-${Date.now()}.png`
    a.click()
  }

  const retake = async () => {
    setCapturedImage(null)
    await startCamera()
  }

  return (
    <div style={styles.app}>
      {screen === 'loading' && (
        <div style={styles.centered}>
          <div style={styles.spinner} />
          <p style={styles.statusText}>{loadingStatus}</p>
        </div>
      )}

      {screen === 'booth' && (
        <div style={styles.boothContainer}>
          <video ref={videoRef} playsInline muted style={styles.hiddenVideo} />

          {cameraError ? (
            <div style={styles.centered}>
              <p style={styles.error}>{cameraError}</p>
              <button onClick={startCamera} style={styles.retryButton}>Retry Camera</button>
            </div>
          ) : (
            <>
              <div style={styles.canvasWrapper}>
                <canvas ref={canvasRef} style={styles.canvas} />
              </div>

              <div style={styles.boothControls}>
                {overlayImages.length > 1 ? (
                  <button onClick={cyclePreview} style={styles.secondaryButton}>
                    Design {previewIndex + 1}/{overlayImages.length}
                  </button>
                ) : (
                  <div style={styles.spacer} />
                )}

                <button onClick={capture} style={styles.captureButton}>
                  <div style={styles.captureButtonInner} />
                </button>

                <div style={styles.spacer} />
              </div>
            </>
          )}
        </div>
      )}

      {screen === 'review' && capturedImage && (
        <div style={styles.reviewContainer}>
          <h2 style={styles.reviewTitle}>Your Magazine Cover</h2>
          <div style={styles.reviewImageWrapper}>
            <img src={capturedImage} alt="Captured" style={styles.reviewImage} />
          </div>
          <div style={styles.reviewControls}>
            <button onClick={retake} style={styles.secondaryButton}>Retake</button>
            <button onClick={download} style={styles.downloadButton}>Download Photo</button>
          </div>
        </div>
      )}
    </div>
  )
}

const styles = {
  app: {
    minHeight: '100vh',
    backgroundColor: '#0a0a0a',
    color: '#e0e0e0',
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    margin: 0,
    padding: 0,
  },
  centered: {
    height: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
  },
  spinner: {
    width: 40,
    height: 40,
    border: '3px solid #333',
    borderTopColor: '#fff',
    borderRadius: '50%',
    animation: 'spin 0.8s linear infinite',
  },
  statusText: {
    fontSize: 14,
    color: '#888',
    letterSpacing: '0.04em',
  },
  error: {
    color: '#ff4444',
    fontSize: 13,
  },
  retryButton: {
    padding: '10px 24px',
    background: '#222',
    border: '1px solid #444',
    borderRadius: 8,
    color: '#ccc',
    fontSize: 13,
    cursor: 'pointer',
  },
  boothContainer: {
    height: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  hiddenVideo: {
    position: 'absolute',
    width: 0,
    height: 0,
    opacity: 0,
    pointerEvents: 'none',
  },
  canvasWrapper: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    padding: 16,
    boxSizing: 'border-box',
  },
  canvas: {
    maxWidth: '100%',
    maxHeight: 'calc(100vh - 120px)',
    borderRadius: 4,
    objectFit: 'contain',
  },
  boothControls: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    maxWidth: 500,
    padding: '16px 24px 32px',
    boxSizing: 'border-box',
  },
  captureButton: {
    width: 72,
    height: 72,
    borderRadius: '50%',
    border: '3px solid #ffffff',
    background: 'transparent',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
  },
  captureButtonInner: {
    width: 58,
    height: 58,
    borderRadius: '50%',
    background: '#ffffff',
  },
  secondaryButton: {
    padding: '10px 20px',
    background: 'transparent',
    border: '1px solid #444',
    borderRadius: 8,
    color: '#aaa',
    fontSize: 13,
    cursor: 'pointer',
    letterSpacing: '0.02em',
    minWidth: 90,
  },
  spacer: {
    width: 90,
  },
  reviewContainer: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  reviewTitle: {
    fontSize: 20,
    fontWeight: 300,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    marginBottom: 24,
    color: '#ccc',
  },
  reviewImageWrapper: {
    maxWidth: '90vw',
    maxHeight: '65vh',
    marginBottom: 32,
  },
  reviewImage: {
    maxWidth: '100%',
    maxHeight: '65vh',
    borderRadius: 4,
    objectFit: 'contain',
  },
  reviewControls: {
    display: 'flex',
    gap: 16,
  },
  downloadButton: {
    padding: '12px 36px',
    background: '#ffffff',
    color: '#000000',
    border: 'none',
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 600,
    letterSpacing: '0.04em',
    cursor: 'pointer',
  },
}

export default App
